# Generated by Django 5.2.4 on 2025-08-07 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=1024)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Procesamiento'), ('PROCESSING', 'Procesando Contenido'), ('AWAITING_APPROVAL', 'Esperando Aprobación'), ('APPROVED', 'Aprobado para Publicar'), ('PUBLISHING', 'Publicando en Redes...'), ('PUBLISHED', 'Publicado Exitosamente'), ('FAILED', 'Misión Fallida')], default='PENDING', max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('hashtags', models.CharField(blank=True, max_length=512)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('facebook_page_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_accounts', models.ManyToManyField(blank=True, to='socialaccount.socialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
