# Generated by Django 5.2.4 on 2025-08-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='facebook_video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='facebook_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
