# Generated by Django 5.2.4 on 2025-08-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_facebook_video_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='youtube_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
