# Generated by Django 5.2.4 on 2025-08-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_youtube_video_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='twitter_tweet_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='twitter_tweet_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
