# Generated by Django 5.2.4 on 2025-08-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_publication_twitter_tweet_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='instagram_media_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='instagram_permalink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
