# Generated by Django 5.2.4 on 2026-01-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_publication_instagram_media_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='video_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
