# Generated by Django 5.2.4 on 2026-01-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_add_video_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
