# Generated by Django 5.2.4 on 2026-01-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_publication_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='tiktok_video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='tiktok_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
