# Generated by Django 5.2.4 on 2026-07-10 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_publication_tiktok_video_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality', models.CharField(choices=[('VIRAL', 'Viral / Clickbait — Títulos impactantes que generan curiosidad'), ('PROFESIONAL', 'Profesional — Tono serio, corporativo y confiable'), ('CASUAL', 'Casual / Cercano — Como hablarle a un amigo'), ('HUMORISTICO', 'Humorístico — Divertido, con chispa y sarcasmo ligero'), ('EDUCATIVO', 'Educativo — Claro, didáctico y aporta valor'), ('INSPIRADOR', 'Inspirador — Motivacional y emotivo'), ('VENTAS', 'Ventas — Persuasivo, orientado a conversión')], default='VIRAL', max_length=20, verbose_name='Personalidad de la IA')),
                ('custom_instructions', models.TextField(blank=True, default='', help_text='Reglas adicionales para la IA: nicho, palabras prohibidas, estilo de marca, llamados a la acción, etc.', verbose_name='Instrucciones personalizadas')),
                ('default_hashtags', models.CharField(blank=True, default='', help_text='Hashtags que SIEMPRE se incluirán, separados por espacios. Ej: #miMarca #prosite', max_length=255, verbose_name='Hashtags fijos')),
                ('hashtags_count', models.PositiveSmallIntegerField(default=3, verbose_name='Cantidad de hashtags generados')),
                ('use_emojis', models.BooleanField(default=True, verbose_name='Usar emojis en título y descripción')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de IA',
                'verbose_name_plural': 'Configuraciones de IA',
            },
        ),
    ]
