# Generated by Django 5.2.4 on 2026-07-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_aiconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('groq', 'Groq (transcripción Whisper)')], max_length=20, unique=True, verbose_name='Proveedor')),
                ('api_key_encrypted', models.TextField(blank=True, default='', verbose_name='API key (cifrada)')),
                ('model_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Modelo')),
                ('status', models.CharField(choices=[('unconfigured', 'Sin configurar'), ('active', 'Activa'), ('invalid', 'Inválida')], default='unconfigured', max_length=15, verbose_name='Estado')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True, verbose_name='Última prueba')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integración API',
                'verbose_name_plural': 'Integraciones API',
            },
        ),
    ]
