# Generated by Django 5.2.4 on 2026-07-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_apiintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='publish_to_instagram',
            field=models.BooleanField(default=False, verbose_name='Publicar en Instagram'),
        ),
    ]
