# Generated by Django 5.2.4 on 2026-07-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_publication_publish_to_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='processing_step',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
