# Generated by Django 5.2.4 on 2026-08-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_publication_processing_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En cola'), ('PROCESSING', 'Procesando'), ('AWAITING_APPROVAL', 'Por aprobar'), ('APPROVED', 'Aprobada'), ('PUBLISHING', 'Publicando'), ('PUBLISHED', 'Publicada'), ('FAILED', 'Falló')], default='PENDING', max_length=30),
        ),
    ]
