# Generated by Django 5.2.4 on 2026-01-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Test')),
                ('script_path', models.CharField(help_text='Ruta relativa desde la raíz del proyecto, ej: testing/test_01_auth.py', max_length=512, verbose_name='Ruta del Script')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'Ejecutando...'), ('PASSED', 'Pasó Exitosamente'), ('FAILED', 'Falló')], default='PENDING', max_length=50, verbose_name='Estado')),
                ('output_log', models.TextField(blank=True, verbose_name='Logs de Ejecución')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Ejecución')),
                ('duration', models.FloatField(default=0.0, verbose_name='Duración (s)')),
            ],
            options={
                'verbose_name': 'Prueba del Sistema',
                'verbose_name_plural': 'Pruebas del Sistema',
                'ordering': ['name'],
            },
        ),
    ]
