# Generated by Django 5.2.4 on 2026-01-15 01:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'Ejecutando...'), ('PASSED', 'Pasó Exitosamente'), ('FAILED', 'Falló')], max_length=50, verbose_name='Estado')),
                ('output_log', models.TextField(blank=True, verbose_name='Logs de Ejecución')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Ejecución')),
                ('duration', models.FloatField(default=0.0, verbose_name='Duración (s)')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='testing_ui.testresult', verbose_name='Test Relacionado')),
            ],
            options={
                'verbose_name': 'Ejecución Histórica',
                'verbose_name_plural': 'Historial de Ejecuciones',
                'ordering': ['-executed_at'],
            },
        ),
    ]
